name: Keep API Alive

on:
  schedule:
    - cron: '*/5 * * * *'  # This cron expression schedules the workflow to run every 5 minutes

jobs:
  ping:
    runs-on: ubuntu-latest  # Specifies the environment for the job

    steps:
      - name: Ping the API
        run: |
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -X GET "https://kestoustd.onrender.com/convert?amount=1000")
          if [ "$RESPONSE" -eq 200 ]; then
            echo "API Pinged successfully at $(date)"
          else
            echo "Failed to ping API at $(date). Response code: $RESPONSE"
            # Placeholder for notification logic (e.g., sending an email or Slack message)
          fi